<a href="https://colab.research.google.com/github/havaledar/ECON3740_W25/blob/main/ECON3740_W25_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [1]:
!pip install wooldridge

Collecting wooldridge
  Downloading wooldridge-0.4.5-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from wooldridge) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->wooldridge) (1.17.0)
Downloading wooldridge-0.4.5-py3-none-any.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 18.1 MB/s eta 0:00:00
Installing collected packages: wooldridge
Successfully installed wooldridge-0.4.5

In [2]:
import wooldridge as woo

In [31]:
import pandas as pd

In [ ]:
import statsmodels.formula.api as smf

# Reading Data

## Wooldridge datasets

In [ ]:
woo.data()

  J.M. Wooldridge (2019) Introductory Econometrics: A Modern Approach,
  Cengage Learning, 6th edition.

  401k       401ksubs    admnrev       affairs     airfare
  alcohol    apple       approval      athlet1     athlet2
  attend     audit       barium        beauty      benefits
  beveridge  big9salary  bwght         bwght2      campus
  card       catholic    cement        census2000  ceosal1
  ceosal2    charity     consump       corn        countymurders
  cps78_85   cps91       crime1        crime2      crime3
  crime4     discrim     driving       earns       econmath
  elem94_95  engin       expendshares  ezanders    ezunem
  fair       fertil1     fertil2       fertil3     fish
  fringe     gpa1        gpa2          gpa3        happiness
  hprice1    hprice2     hprice3       hseinv      htv
  infmrt     injury      intdef        intqrt      inven
  jtrain     jtrain2     jtrain3       kielmc      lawsch85
  loanapp    lowbrth     mathpnl       meap00_01   meap01
  meap93     meapsingle  minwage       mlb1        mroz
  murder     nbasal      nyse          okun        openness
  pension    phillips    pntsprd       prison      prminwge
  rdchem     rdtelec     recid         rental      return
  saving     sleep75     slp75_81      smoke       traffic1
  traffic2   twoyear     volat         vote1       vote2
  voucher    wage1       wage2         wagepan     wageprc
  wine

In [19]:
data = woo.data('wage1')

In [ ]:
woo.data('wage1', description=True)

name of dataset: wage1
no of variables: 24
no of observations: 526

+----------+---------------------------------+
| variable | label                           |
+----------+---------------------------------+
| wage     | average hourly earnings         |
| educ     | years of education              |
| exper    | years potential experience      |
| tenure   | years with current employer     |
| nonwhite | =1 if nonwhite                  |
| female   | =1 if female                    |
| married  | =1 if married                   |
| numdep   | number of dependents            |
| smsa     | =1 if live in SMSA              |
| northcen | =1 if live in north central U.S |
| south    | =1 if live in southern region   |
| west     | =1 if live in western region    |
| construc | =1 if work in construc. indus.  |
| ndurman  | =1 if in nondur. manuf. indus.  |
| trcommpu | =1 if in trans, commun, pub ut  |
| trade    | =1 if in wholesale or retail    |
| services | =1 if in services indus.        |
| profserv | =1 if in prof. serv. indus.     |
| profocc  | =1 if in profess. occupation    |
| clerocc  | =1 if in clerical occupation    |
| servocc  | =1 if in service occupation     |
| lwage    | log(wage)                       |
| expersq  | exper^2                         |
| tenursq  | tenure^2                        |
+----------+---------------------------------+

These are data from the 1976 Current Population Survey, collected by
Henry Farber when he and I were colleagues at MIT in 1988.

In [ ]:
data

## CSV and Excel files

In [ ]:
data = pd.read_csv('URL')

# Manipulating Data in Pandas

The syntax in Pandas is similar to base Python. For example:

- Comparison operators like == for equals
- Assignment with =
- Commenting with # (shortcut key: Ctrl + /)

## Basic

In [ ]:
1 == 2-1

True

In [ ]:
1 = 2-1

This is not a comment.

In [ ]:
This is not a comment.

In [ ]:
# This is a comment.

In [ ]:
4/2
#4+2
#4-2
#4*2

2.0

In [ ]:
import numpy as np

np.log(4)

1.3862943611198906

## Copy

You can make copies like this:

```python
data_copy = data
```

In [ ]:
data_copy = data

## Getting a glimpse of the data

### head

To view the first few rows:

```python
data.head()
```

In [20]:
data.head()

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,trcommpu,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
0,3.10,11,2,0,0,1,0,2,1,0,...,0,0,0,0,0,0,0,1.131402,4,0
1,3.24,12,22,2,0,1,1,3,1,0,...,0,0,1,0,0,0,1,1.175573,484,4
2,3.00,11,2,0,0,0,0,2,0,0,...,0,1,0,0,0,0,0,1.098612,4,0
3,6.00,8,44,28,0,0,1,0,1,0,...,0,0,0,0,0,1,0,1.791759,1936,784
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1.667707,49,4

## Tail

In [10]:
data.tail()

,dcode,bcode,math4,read4,lunch,enroll,expend,exppp,lenroll,lexpend,lexppp,enroll10
1818,83010.0,2024,93.599998,57.400002,50.529999,285,1484497.0,5208.761230,5.652489,14.210587,8.558097,2850
1819,83010.0,2210,69.000000,48.799999,53.670002,259,1279763.0,4941.169922,5.556828,14.062185,8.505358,2590
1820,83010.0,2480,72.500000,63.400002,46.849998,254,1241369.0,4887.279297,5.537334,14.031725,8.494391,2540
1821,83010.0,5101,81.000000,73.800003,34.299999,277,1312697.0,4738.978516,5.624018,14.087594,8.463577,2770
1822,83070.0,2527,88.099998,56.700001,52.920002,650,1660206.0,2554.163086,6.476973,14.322453,7.845480,6500

### info
Get concise summary
```
data.info()
```

In [ ]:
data.info()

## Column operations

## Columns' names

In [21]:
data.columns

Index(['wage', 'educ', 'exper', 'tenure', 'nonwhite', 'female', 'married',
       'numdep', 'smsa', 'northcen', 'south', 'west', 'construc', 'ndurman',
       'trcommpu', 'trade', 'services', 'profserv', 'profocc', 'clerocc',
       'servocc', 'lwage', 'expersq', 'tenursq'],
      dtype='object')

### drop

In [22]:
# Drop the 'CMA' column from DataFrame d1
d1 = data.drop(columns=['services'])
d1

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,ndurman,trcommpu,trade,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
0,3.10,11,2,0,0,1,0,2,1,0,...,0,0,0,0,0,0,0,1.131402,4,0
1,3.24,12,22,2,0,1,1,3,1,0,...,0,0,0,0,0,0,1,1.175573,484,4
2,3.00,11,2,0,0,0,0,2,0,0,...,0,0,1,0,0,0,0,1.098612,4,0
3,6.00,8,44,28,0,0,1,0,1,0,...,0,0,0,0,0,1,0,1.791759,1936,784
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1.667707,49,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,15.00,16,14,2,0,1,1,2,0,0,...,0,0,0,1,1,0,0,2.708050,196,4
522,2.27,10,2,0,0,1,0,3,0,0,...,0,0,1,0,1,0,0,0.819780,4,0
523,4.67,15,13,18,0,0,1,3,0,0,...,0,0,0,0,1,0,0,1.541159,169,324
524,11.56,16,5,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,2.447551,25,1
525,3.50,14,5,4,1,1,0,2,0,0,...,0,0,0,1,0,1,0,1.252763,25,16

### New column

In [7]:
# Create a new column 'NOC_10_5' by multiplying 'NOC_10' by 5
data['wage1000'] = data['wage'] * 10
data.head()

,dcode,bcode,math4,read4,lunch,enroll,expend,exppp,lenroll,lexpend,lexppp,enroll10
0,1010.0,4937,83.300003,77.800003,40.599998,468,2747475.0,5870.672852,6.148468,14.826193,8.677725,4680
1,2070.0,597,90.300003,82.300003,27.100000,679,1505772.0,2217.631836,6.520621,14.224816,7.704195,6790
2,2080.0,4860,61.900002,71.400002,41.750000,400,2121871.0,5304.677734,5.991465,14.567809,8.576344,4000
3,3010.0,790,85.699997,60.000000,12.750000,251,1211034.0,4824.836426,5.525453,14.006985,8.481532,2510
4,3010.0,1403,77.300003,59.099998,17.080000,439,1913501.0,4358.771973,6.084499,14.464445,8.379946,4390

## Selecting more than 1 column

In [8]:
data[['wage', 'wage1000']]

      enroll  enroll10
0        468      4680
1        679      6790
2        400      4000
3        251      2510
4        439      4390
...      ...       ...
1818     285      2850
1819     259      2590
1820     254      2540
1821     277      2770
1822     650      6500

[1823 rows x 2 columns]

## unique

In [27]:
data['numdep'].unique()

array([2, 3, 0, 1, 5, 4, 6])

## value_count

Tabulate the Labour Force Status

In [26]:
data['numdep'].value_counts()

numdep
0    252
1    105
2     99
3     45
4     16
5      7
6      2
Name: count, dtype: int64

## Sort

#### Sort index

In [28]:
data['numdep'].value_counts().sort_index()

numdep
0    252
1    105
2     99
3     45
4     16
5      7
6      2
Name: count, dtype: int64

#### Sort value

In [29]:
data['numdep'].value_counts().sort_values()

numdep
6      2
5      7
4     16
3     45
2     99
1    105
0    252
Name: count, dtype: int64

## Crosstab

In [32]:
pd.crosstab(data['female'], data['married'])

married    0    1
female
0         86  188
1        120  132

### Column

In [36]:
pd.crosstab(data['female'], data['married'], normalize='columns')

married         0       1
female
0        0.417476  0.5875
1        0.582524  0.4125

### Row

In [37]:
pd.crosstab(data['female'], data['married'], normalize='index')

married         0         1
female
0        0.313869  0.686131
1        0.476190  0.523810

## Filter

## Logical operation

1.   & (AND): Logical AND. Returns True when both conditions are True.
2.   \| (OR): Logical OR. Returns True when at least one of the conditions is True.
3.   ~ (NOT): Logical NOT. Inverts the boolean values (True becomes False and vice versa).

## Multiple filters

In [39]:
data[(data['wage'] > 1) & (data['wage'] <= 2)]

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,trcommpu,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
46,1.67,10,1,0,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0.512824,1,0
50,1.63,12,18,0,0,1,0,2,0,0,...,0,0,1,0,0,0,1,0.488580,324,0
69,2.00,12,3,2,0,1,0,4,1,0,...,0,0,1,0,0,0,0,0.693147,9,4
127,1.50,8,31,30,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0.405465,961,900
146,2.00,10,3,0,1,1,0,5,1,0,...,0,1,0,0,0,0,1,0.693147,9,0
165,2.00,13,2,6,0,1,0,0,1,1,...,0,0,1,0,0,0,1,0.693147,4,36
247,1.96,11,38,3,1,1,0,0,0,0,...,0,0,1,0,0,0,0,0.672944,1444,9
288,2.00,9,2,0,0,0,0,3,0,1,...,0,1,0,0,0,0,1,0.693147,4,0
452,1.50,12,11,1,0,1,1,2,0,1,...,0,0,0,1,0,0,1,0.405465,121,1
501,1.75,11,2,1,0,0,0,2,1,0,...,0,1,0,0,0,0,1,0.559616,4,1
515,1.43,12,17,0,0,1,1,2,0,0,...,0,1,0,0,0,0,0,0.357674,289,0

# Regression

In [40]:
# Create the model
model = smf.ols('wage ~ exper', data)

# Fit the model
results = model.fit()

# Display regression results
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   wage   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     6.766
Date:                Fri, 17 Jan 2025   Prob (F-statistic):            0.00955
Time:                        13:17:42   Log-Likelihood:                -1429.7
No. Observations:                 526   AIC:                             2863.
Df Residuals:                     524   BIC:                             2872.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.3733      0.257     20.908      0.000       4.868       5.878
exper          0.0307      0.012      2.601      0.010       0.008       0.054
==============================================================================
Omnibus:                      222.603   Durbin-Watson:                   1.808
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              851.542
Skew:                           1.962   Prob(JB):                    1.23e-185
Kurtosis:                       7.843   Cond. No.                         35.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.