<a href="https://colab.research.google.com/github/havaledar/ECON3740_W25/blob/main/ECON3740_W25_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [ ]:
!pip install wooldridge

Collecting wooldridge
  Downloading wooldridge-0.4.5-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from wooldridge) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->wooldridge) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->wooldridge) (1.17.0)
Downloading wooldridge-0.4.5-py3-none-any.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 26.1 MB/s eta 0:00:00
Installing collected packages: wooldridge
Successfully installed wooldridge-0.4.5

In [ ]:
import wooldridge as woo

In [ ]:
import pandas as pd

In [ ]:
import statsmodels.formula.api as smf

# Reading Data

## Wooldridge datasets

In [ ]:
woo.data()

  J.M. Wooldridge (2019) Introductory Econometrics: A Modern Approach,
  Cengage Learning, 6th edition.

  401k       401ksubs    admnrev       affairs     airfare
  alcohol    apple       approval      athlet1     athlet2
  attend     audit       barium        beauty      benefits
  beveridge  big9salary  bwght         bwght2      campus
  card       catholic    cement        census2000  ceosal1
  ceosal2    charity     consump       corn        countymurders
  cps78_85   cps91       crime1        crime2      crime3
  crime4     discrim     driving       earns       econmath
  elem94_95  engin       expendshares  ezanders    ezunem
  fair       fertil1     fertil2       fertil3     fish
  fringe     gpa1        gpa2          gpa3        happiness
  hprice1    hprice2     hprice3       hseinv      htv
  infmrt     injury      intdef        intqrt      inven
  jtrain     jtrain2     jtrain3       kielmc      lawsch85
  loanapp    lowbrth     mathpnl       meap00_01   meap01
  meap93     meapsingle  minwage       mlb1        mroz
  murder     nbasal      nyse          okun        openness
  pension    phillips    pntsprd       prison      prminwge
  rdchem     rdtelec     recid         rental      return
  saving     sleep75     slp75_81      smoke       traffic1
  traffic2   twoyear     volat         vote1       vote2
  voucher    wage1       wage2         wagepan     wageprc
  wine

In [ ]:
data = woo.data('wage1')

In [ ]:
woo.data('wage1', description=True)

name of dataset: wage1
no of variables: 24
no of observations: 526

+----------+---------------------------------+
| variable | label                           |
+----------+---------------------------------+
| wage     | average hourly earnings         |
| educ     | years of education              |
| exper    | years potential experience      |
| tenure   | years with current employer     |
| nonwhite | =1 if nonwhite                  |
| female   | =1 if female                    |
| married  | =1 if married                   |
| numdep   | number of dependents            |
| smsa     | =1 if live in SMSA              |
| northcen | =1 if live in north central U.S |
| south    | =1 if live in southern region   |
| west     | =1 if live in western region    |
| construc | =1 if work in construc. indus.  |
| ndurman  | =1 if in nondur. manuf. indus.  |
| trcommpu | =1 if in trans, commun, pub ut  |
| trade    | =1 if in wholesale or retail    |
| services | =1 if in services indus.        |
| profserv | =1 if in prof. serv. indus.     |
| profocc  | =1 if in profess. occupation    |
| clerocc  | =1 if in clerical occupation    |
| servocc  | =1 if in service occupation     |
| lwage    | log(wage)                       |
| expersq  | exper^2                         |
| tenursq  | tenure^2                        |
+----------+---------------------------------+

These are data from the 1976 Current Population Survey, collected by
Henry Farber when he and I were colleagues at MIT in 1988.

## CSV and Excel files

In [ ]:
data = pd.read_excel('https://cengage-dps.s3.amazonaws.com/economics/690273_wooldridge_8e/meap01_v1.xlsx')

In [ ]:
data

,dcode,bcode,math4,read4,lunch,enroll,expend,exppp,lenroll,lexpend,lexppp
0,9010,6966,69.3,50.7,41.02,529,2693848,5092.340,6.270988,14.80648,8.535493
1,82050,944,71.4,61.9,13.86,498,2932629,5888.813,6.210600,14.89141,8.680810
2,74100,8355,82.0,64.0,15.41,266,1315493,4945.462,5.583496,14.08972,8.506226
3,41090,393,89.8,86.4,4.95,303,2046656,6754.640,5.713733,14.53172,8.817985
4,82010,4812,58.2,40.0,76.61,560,3497356,6245.279,6.327937,15.06752,8.739581
...,...,...,...,...,...,...,...,...,...,...,...
1726,50020,4356,83.0,66.0,45.81,334,1889077,5655.919,5.811141,14.45160,8.640458
1727,52170,3479,94.9,76.9,23.30,206,1202158,5835.718,5.327876,13.99963,8.671753
1728,82010,3390,71.4,51.0,85.32,620,4008713,6465.666,6.429719,15.20398,8.774261
1729,82050,1642,66.2,60.6,14.29,567,2480613,4374.979,6.340359,14.72402,8.383657
1730,61210,5368,65.3,46.7,23.77,366,1796875,4909.495,5.902633,14.40156,8.498926

# Manipulating Data in Pandas

The syntax in Pandas is similar to base Python. For example:

- Comparison operators like == for equals
- Assignment with =
- Commenting with # (shortcut key: Ctrl + /)

## Basic

In [ ]:
1 == 2-1

True

In [ ]:
1 = 2-1

This is not a comment.

In [ ]:
This is not a comment.

In [ ]:
# This is a comment.

In [ ]:
# 4/2
# 4+2
# 4-2
4*2

8

In [ ]:
import numpy as np

In [ ]:
np.log(4)

1.3862943611198906

## Copy

You can make copies like this:

```python
data_copy = data
```

In [ ]:
data_copy = data

## Getting a glimpse of the data

### head

To view the first few rows:

```python
data.head()
```

In [ ]:
data.head()

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,trcommpu,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
0,3.10,11,2,0,0,1,0,2,1,0,...,0,0,0,0,0,0,0,1.131402,4,0
1,3.24,12,22,2,0,1,1,3,1,0,...,0,0,1,0,0,0,1,1.175573,484,4
2,3.00,11,2,0,0,0,0,2,0,0,...,0,1,0,0,0,0,0,1.098612,4,0
3,6.00,8,44,28,0,0,1,0,1,0,...,0,0,0,0,0,1,0,1.791759,1936,784
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1.667707,49,4

## Tail

In [ ]:
data.tail()

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,trcommpu,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
521,15.00,16,14,2,0,1,1,2,0,0,...,0,0,0,1,1,0,0,2.708050,196,4
522,2.27,10,2,0,0,1,0,3,0,0,...,0,1,0,0,1,0,0,0.819780,4,0
523,4.67,15,13,18,0,0,1,3,0,0,...,0,0,0,0,1,0,0,1.541159,169,324
524,11.56,16,5,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,2.447551,25,1
525,3.50,14,5,4,1,1,0,2,0,0,...,0,0,0,1,0,1,0,1.252763,25,16

### info
Get concise summary
```
data.info()
```

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 24 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   wage      526 non-null    float64
 1   educ      526 non-null    int64
 2   exper     526 non-null    int64
 3   tenure    526 non-null    int64
 4   nonwhite  526 non-null    int64
 5   female    526 non-null    int64
 6   married   526 non-null    int64
 7   numdep    526 non-null    int64
 8   smsa      526 non-null    int64
 9   northcen  526 non-null    int64
 10  south     526 non-null    int64
 11  west      526 non-null    int64
 12  construc  526 non-null    int64
 13  ndurman   526 non-null    int64
 14  trcommpu  526 non-null    int64
 15  trade     526 non-null    int64
 16  services  526 non-null    int64
 17  profserv  526 non-null    int64
 18  profocc   526 non-null    int64
 19  clerocc   526 non-null    int64
 20  servocc   526 non-null    int64
 21  lwage     526 non-null    float64
 22  expersq   526 non-null    int64
 23  tenursq   526 non-null    int64
dtypes: float64(2), int64(22)
memory usage: 98.8 KB

## Column operations

## Columns' names

In [ ]:
data.columns

Index(['wage', 'educ', 'exper', 'tenure', 'nonwhite', 'female', 'married',
       'numdep', 'smsa', 'northcen', 'south', 'west', 'construc', 'ndurman',
       'trcommpu', 'trade', 'services', 'profserv', 'profocc', 'clerocc',
       'servocc', 'lwage', 'expersq', 'tenursq'],
      dtype='object')

### drop

In [ ]:
d1 = data.drop(columns=['services'])
d1

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,ndurman,trcommpu,trade,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
0,3.10,11,2,0,0,1,0,2,1,0,...,0,0,0,0,0,0,0,1.131402,4,0
1,3.24,12,22,2,0,1,1,3,1,0,...,0,0,0,0,0,0,1,1.175573,484,4
2,3.00,11,2,0,0,0,0,2,0,0,...,0,0,1,0,0,0,0,1.098612,4,0
3,6.00,8,44,28,0,0,1,0,1,0,...,0,0,0,0,0,1,0,1.791759,1936,784
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1.667707,49,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,15.00,16,14,2,0,1,1,2,0,0,...,0,0,0,1,1,0,0,2.708050,196,4
522,2.27,10,2,0,0,1,0,3,0,0,...,0,0,1,0,1,0,0,0.819780,4,0
523,4.67,15,13,18,0,0,1,3,0,0,...,0,0,0,0,1,0,0,1.541159,169,324
524,11.56,16,5,1,0,0,1,0,0,0,...,1,0,0,0,0,0,0,2.447551,25,1
525,3.50,14,5,4,1,1,0,2,0,0,...,0,0,0,1,0,1,0,1.252763,25,16

### New column

In [ ]:
data['wage1000'] = data['wage'] * 1000
data.head()

,wage,educ,exper,tenure,nonwhite,female,married,numdep,northcen,south,...,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq,wage1000
0,3.10,11,2,0,0,1,0,2,0,0,...,0,0,0,0,0,0,1.131402,4,0,3099.999905
1,3.24,12,22,2,0,1,1,3,0,0,...,0,1,0,0,0,1,1.175573,484,4,3240.000010
2,3.00,11,2,0,0,0,0,2,0,0,...,1,0,0,0,0,0,1.098612,4,0,3000.000000
3,6.00,8,44,28,0,0,1,0,0,0,...,0,0,0,0,1,0,1.791759,1936,784,6000.000000
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,1.667707,49,4,5300.000191

## Selecting more than 1 column

In [ ]:
data[['wage', 'wage1000']]

      wage      wage1000
0     3.10   3099.999905
1     3.24   3240.000010
2     3.00   3000.000000
3     6.00   6000.000000
4     5.30   5300.000191
..     ...           ...
521  15.00  15000.000000
522   2.27   2269.999981
523   4.67   4670.000076
524  11.56  11560.000420
525   3.50   3500.000000

[526 rows x 2 columns]

## unique

In [ ]:
data['numdep'].unique()

array([2, 3, 0, 1, 5, 4, 6])

## value_count

Tabulate the Labour Force Status

In [ ]:
data['numdep'].value_counts()

numdep
0    252
1    105
2     99
3     45
4     16
5      7
6      2
Name: count, dtype: int64

## Sort

#### Sort index

In [ ]:
data['numdep'].value_counts().sort_index()

numdep
0    252
1    105
2     99
3     45
4     16
5      7
6      2
Name: count, dtype: int64

#### Sort value

In [ ]:
data['numdep'].value_counts().sort_values()

numdep
6      2
5      7
4     16
3     45
2     99
1    105
0    252
Name: count, dtype: int64

## Crosstab

In [ ]:
data['female'].value_counts()

female
0    274
1    252
Name: count, dtype: int64

In [ ]:
data['married'].value_counts()

married
1    320
0    206
Name: count, dtype: int64

In [ ]:
pd.crosstab(data['female'], data['married'])

married    0    1
female
0         86  188
1        120  132

### Column

In [ ]:
pd.crosstab(data['female'], data['married'], normalize='columns')

married         0       1
female
0        0.417476  0.5875
1        0.582524  0.4125

### Row

In [ ]:
pd.crosstab(data['female'], data['married'], normalize='index')

married         0         1
female
0        0.313869  0.686131
1        0.476190  0.523810

## Filter

## Logical operation

1.   & (AND): Logical AND. Returns True when both conditions are True.
2.   \| (OR): Logical OR. Returns True when at least one of the conditions is True.
3.   ~ (NOT): Logical NOT. Inverts the boolean values (True becomes False and vice versa).

## Multiple filters

In [ ]:
data[(data['wage'] > 1) | (data['wage'] <= 2)]

,wage,educ,exper,tenure,nonwhite,female,married,numdep,northcen,south,...,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq,wage1000
0,3.10,11,2,0,0,1,0,2,0,0,...,0,0,0,0,0,0,1.131402,4,0,3099.999905
1,3.24,12,22,2,0,1,1,3,0,0,...,0,1,0,0,0,1,1.175573,484,4,3240.000010
2,3.00,11,2,0,0,0,0,2,0,0,...,1,0,0,0,0,0,1.098612,4,0,3000.000000
3,6.00,8,44,28,0,0,1,0,0,0,...,0,0,0,0,1,0,1.791759,1936,784,6000.000000
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,1.667707,49,4,5300.000191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,15.00,16,14,2,0,1,1,2,0,0,...,0,0,1,1,0,0,2.708050,196,4,15000.000000
522,2.27,10,2,0,0,1,0,3,0,0,...,1,0,0,1,0,0,0.819780,4,0,2269.999981
523,4.67,15,13,18,0,0,1,3,0,0,...,0,0,0,1,0,0,1.541159,169,324,4670.000076
524,11.56,16,5,1,0,0,1,0,0,0,...,0,0,0,0,0,0,2.447551,25,1,11560.000420
525,3.50,14,5,4,1,1,0,2,0,0,...,0,0,1,0,1,0,1.252763,25,16,3500.000000

# Regression

In [ ]:
# Create the model
model = smf.ols('wage ~ exper', data)

# Fit the model
results = model.fit()

# Display regression results
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   wage   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     6.766
Date:                Fri, 17 Jan 2025   Prob (F-statistic):            0.00955
Time:                        13:17:42   Log-Likelihood:                -1429.7
No. Observations:                 526   AIC:                             2863.
Df Residuals:                     524   BIC:                             2872.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.3733      0.257     20.908      0.000       4.868       5.878
exper          0.0307      0.012      2.601      0.010       0.008       0.054
==============================================================================
Omnibus:                      222.603   Durbin-Watson:                   1.808
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              851.542
Skew:                           1.962   Prob(JB):                    1.23e-185
Kurtosis:                       7.843   Cond. No.                         35.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.